spring:
  application:
    name: maze-repair

---

spring:
  config:
    activate:
      on-profile: local

# Add your own logging levels for your packages.
logging:
  level:
    org.springframework.boot: info